Tabela Imovel e as relações com Foreign Keys
estagio-2023/app-casas pull request #9
Opened 2024-01-09 22:47 UTC by pmzpro

2024-01-09 23:44 UTC, Silva096 commented on BaseDados/Código/Readme
> +	ADD CONSTRAINT fk_imovel_id FOREIGN KEY (fk_imovel_id) REFERENCES imovel(imovel_id)
A configuração da foreign key das comodidades está em falta.

2024-01-10 16:57 UTC, Silva096 commented on BaseDados/Código/Readme
> +	ADD CONSTRAINT fk_comodidades_id FOREIGN KEY (fk_comodidades_id) REFERENCES comodidades(id);
Em vez de teres dois ALTER TABLE à mesma tabela, podes juntar da seguinte forma:
`ALTER TABLE Imovel_Has_Comodidades 
	ADD CONSTRAINT fk_imovel_id FOREIGN KEY (fk_imovel_id) REFERENCES imovel(imovel_id),
	ADD CONSTRAINT fk_comodidades_id FOREIGN KEY (fk_comodidades_id) REFERENCES comodidades(id);
`

2024-01-10 21:47 UTC, Silva096 requested changes

2024-01-10 21:47 UTC, Silva096 commented on BaseDados/Código/Readme
> +ADD CONSTRAINT fk_tipologia_id FOREIGN KEY (fk_tipologia_id) REFERENCES tipologia(id),
Tem uma vírgula no fim a mais, corrige por favor Pedro

2024-01-10 21:47 UTC, Silva096 commented on BaseDados/Código/Readme
> +CREATE TABLE IMOVEL (
O nome da tabela tem de ficar em minúsculas tal como as outras.
Altera 'IMOVEL' para 'imovel' por favor

2024-01-11 09:10 UTC, Silva096 approved these changes

2024-01-11 11:07 UTC, jonathan-osorio approved these changes

2024-01-12 09:41 UTC, merged